// Pre-warms the engine's derived data caches for shipping.
//
// Runs the built wasm engine once under node with -builddb (plain MEMFS —
// wasm/pre.js skips the IDBFS mount when there's no indexedDB), then captures
// everything the run wrote under /crawl into wasm/dist/prewarm/ plus a
// manifest.json. The client seeds these files into a device's IDBFS on first
// boot (Module.pocketzotSeedCaches), so no device ever pays the multi-second
// description-DB + des-cache build.
//
// The caches validate against file_modtime() == POCKETZOT_DAT_STAMP baked
// into this same build (files.cc), which is why they MUST be generated by
// the wasm engine itself — a native crawl's caches would embed real mtimes
// (and its host sqlite's file format) and fail validation. manifest.stamp
// records the build's dat stamp (wasm/build/dat-stamp) so the client can
// re-seed IDBFS after an engine update instead of letting the engine fall
// back to a full in-browser rebuild.
//
// Run from crawl-ref/source, after make -f wasm/Makefile.emscripten:
//   node wasm/bake-caches.mjs

import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const wasmDir = dirname(fileURLToPath(import.meta.url))
const distDir = join(wasmDir, 'dist')
const prewarmDir = join(distDir, 'prewarm')
const stamp = readFileSync(join(wasmDir, 'build', 'dat-stamp'), 'utf8').trim()

const factory = (await import(join(distDir, 'crawl.js'))).default

const wasmBinary = readFileSync(join(distDir, 'crawl.wasm'))
const dataBuf = readFileSync(join(distDir, 'crawl.data'))

let exitCode = null
let resolveExit
const exited = new Promise(r => { resolveExit = r })

const module_ = await factory({
  arguments: [
    '-headless',
    '-webtiles-socket', 'pocketzot',
    '-dir', '/crawl',
    '-name', 'local',
    '-builddb',
  ],
  wasmBinary,
  getPreloadedPackage: () =>
    dataBuf.buffer.slice(dataBuf.byteOffset, dataBuf.byteOffset + dataBuf.byteLength),
  pocketzotOnOutput: () => {}, // -builddb emits nothing, but be safe
  print: line => console.log('[engine]', line),
  printErr: line => console.error('[engine]', line),
  onExit: code => { exitCode = code; resolveExit() },
})

await exited
if (exitCode !== 0)
  throw new Error(`engine -builddb run exited with code ${exitCode}`)

// Capture everything the run wrote under /crawl. The run started from an
// empty MEMFS dir, so all of it is derived first-boot state (db/*, des
// cache) — exactly what a fresh device would otherwise build for itself.
const FS = module_.FS
const files = []
const walk = dir => {
  for (const name of FS.readdir(dir)) {
    if (name === '.' || name === '..') continue
    const path = `${dir}/${name}`
    if (FS.isDir(FS.stat(path).mode)) walk(path)
    else files.push(path)
  }
}
walk('/crawl')

// Pack everything into one blob + an offset manifest: the des cache alone is
// ~550 small files, and the client seeds on first boot with two fetches
// (manifest + pack) instead of one per file.
files.sort()
rmSync(prewarmDir, { recursive: true, force: true })
mkdirSync(prewarmDir, { recursive: true })
const chunks = []
const manifestFiles = []
let offset = 0
for (const path of files) {
  const bytes = FS.readFile(path) // Uint8Array
  chunks.push(bytes)
  manifestFiles.push({ path: path.slice('/crawl/'.length), offset, size: bytes.length })
  offset += bytes.length
}

writeFileSync(join(prewarmDir, 'prewarm.bin'), Buffer.concat(chunks))
writeFileSync(
  join(prewarmDir, 'manifest.json'),
  JSON.stringify({ stamp, files: manifestFiles }) + '\n',
)

console.log(`baked ${manifestFiles.length} cache files into prewarm.bin, ` +
  `${(offset / 1024 / 1024).toFixed(1)} MB, stamp ${stamp} -> ${prewarmDir}`)
